services:
  - type: web
    name: real-estate-mern
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: VITE_FIREBASE_API_KEY
        sync: false
    


